version: "2"
services:
  test-env:
    image: 'hub.opshub.sh/binary/v1/containerops/component/binary/php:0.1'
    build: ./
    container_name: test-env
    tty: true
    environment:
      - "TZ=Asia/Shanghai"
    volumes:
      - ../../../:/root/src
